version: '3'
services:
  # This is capable to relay via gmail, Amazon SES, or generic relays
  # See: https://hub.docker.com/r/ixdotai/smtp
  mail:
    image: ixdotai/smtp
    environment:
      - "SMARTHOST_ADDRESS=${SMARTHOST_ADDRESS}"
      - "SMARTHOST_PORT=${SMARTHOST_PORT}"
      - "SMARTHOST_USER=${SMARTHOST_USER}"
      - "SMARTHOST_PASSWORD=${SMARTHOST_PASSWORD}"
      - "SMARTHOST_ALIASES=${SMARTHOST_ALIASES}"

  redis:
    image: redis:5.0.6

  db:
    # We use MariaDB because it supports ARM and has the expected collations
    image: mariadb:10.8.2
    restart: always
    environment:
      - "MYSQL_USER=misp"
      - "MYSQL_PASSWORD=example"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=misp"
    volumes:
      - mysql_data:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE Prevent runaway mysql log

  misp:
    image: ostefano/misp-docker:core-latest
    depends_on:
      - redis
      - db
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./configs/:/var/www/MISP/app/Config/:delegated"
      - "./logs/:/var/www/MISP/app/tmp/logs/:delegated"
      - "./files/:/var/www/MISP/app/files/:delegated"
      - "./ssl/:/etc/nginx/certs/:delegated"
#      - "./examples/custom-entrypoint.sh:/custom-entrypoint.sh" # Use the example custom-entrypoint.sh
      - "./.gnupg/:/var/www/MISP/.gnupg/:delegated"
    environment:
      - "HOSTNAME=https://localhost"
      - "REDIS_FQDN=redis"
      - "INIT=true"             # Initialze MISP, things includes, attempting to import SQL and the Files DIR
      - "CRON_USER_ID=1"        # The MISP user ID to run cron jobs as
      # Synchronization Servers settings
      - "SYNCSERVERS=1"
      - "SYNCSERVERS_1_NAME=${SYNCSERVERS_1_NAME}"
      - "SYNCSERVERS_1_UUID=${SYNCSERVERS_1_UUID}"
      - "SYNCSERVERS_1_KEY=${SYNCSERVERS_1_KEY}"
      - |
        SYNCSERVERS_1_DATA=
        {
          "url": "https://intel.thedfirreport.com/",
          "pull_rules": "{\"tags\":{\"OR\":[],\"NOT\":[]},\"orgs\":{\"OR\":[],\"NOT\":[]},\"url_params\":\"{\\\"searchanalysis\\\": \\\"2\\\"}\"}",
          "pull": true
        }
      # Database Configuration (And their defaults)
#      - "MYSQL_HOST=db"
#      - "MYSQL_USER=misp"
#      - "MYSQL_PASSWORD=example" # NOTE: This should be AlphaNum with no Special Chars. Otherwise, edit config files after first run. 
#      - "MYSQL_DATABASE=misp"
      # Optional Settings
#      - "NOREDIR=true" # Do not redirect port 80
#      - "DISIPV6=true" # Disable IPV6 in nginx
#      - "CERTAUTH=optional" # Can be set to optional or on - Step 2 of https://github.com/MISP/MISP/tree/2.4/app/Plugin/CertAuth is still required
#      - "SECURESSL=true" # Enable higher security SSL in nginx
#      - "MISP_MODULES_FQDN=http://misp-modules" # Set the MISP Modules FQDN, used for Enrichment_services_url/Import_services_url/Export_services_url
#      - "WORKERS=1" # Legacy variable controlling the number of parallel workers (use variables below instead)
#      - "NUM_WORKERS_DEFAULT=5"    # To set the number of default workers
#      - "NUM_WORKERS_PRIO=5"       # To set the number of prio workers
#      - "NUM_WORKERS_EMAIL=5"      # To set the number of email workers
#      - "NUM_WORKERS_UPDATE=1"     # To set the number of update workers
#      - "NUM_WORKERS_CACHE=5"      # To set the number of cache workers
      # Custom Settings
      - "ADMIN_EMAIL=${ADMIN_EMAIL}"
      - "ADMIN_KEY=${ADMIN_KEY}"
      - "ADMIN_ORG=${ADMIN_ORG}"
      - "GPG_PASSPHRASE=${GPG_PASSPHRASE}"
      - "NSX_ANALYSIS_API_TOKEN=${NSX_ANALYSIS_API_TOKEN}"
      - "NSX_ANALYSIS_KEY=${NSX_ANALYSIS_KEY}"
      - "VIRUSTOTAL_KEY=${VIRUSTOTAL_KEY}"
  misp-modules:
    image: ostefano/misp-docker:modules-latest
    environment:
      - "REDIS_BACKEND=redis"
    depends_on:
      - redis
      - db

volumes:
    mysql_data:
