version: '3'
services:
  # This is capable to relay via gmail, Amazon SES, or generic relays
  # See: https://hub.docker.com/r/ixdotai/smtp
  mail:
    image: ixdotai/smtp
    environment:
      - "SMARTHOST_ADDRESS=${SMARTHOST_ADDRESS}"
      - "SMARTHOST_PORT=${SMARTHOST_PORT}"
      - "SMARTHOST_USER=${SMARTHOST_USER}"
      - "SMARTHOST_PASSWORD=${SMARTHOST_PASSWORD}"
      - "SMARTHOST_ALIASES=${SMARTHOST_ALIASES}"

  redis:
    image: redis:5.0.6

  db:
    # We use MariaDB because it supports ARM and has the expected collations
    image: mariadb:10.8.2
    restart: always
    environment:
      - "MYSQL_USER=misp"
      - "MYSQL_PASSWORD=example"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=misp"
    volumes:
      - mysql_data:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE Prevent runaway mysql log

  misp:
    image: ostefano/misp-docker:core-latest
    build:
      context: server/.
      args:
          - MISP_TAG=${MISP_TAG}
          - MISP_COMMIT=${MISP_COMMIT}
          - PHP_VER=${PHP_VER}
    depends_on:
      - redis
      - db
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./configs/:/var/www/MISP/app/Config/"
      - "./logs/:/var/www/MISP/app/tmp/logs/"
      - "./files/:/var/www/MISP/app/files/"
      - "./ssl/:/etc/nginx/certs/"
      - "./gnupg/:/var/www/MISP/.gnupg/"
      - "${PUBLIC_MOUNT_POINT}:/mnt/public/"
#      - "./examples/custom-entrypoint.sh:/custom-entrypoint.sh" # Use the example custom-entrypoint.sh
    environment:
      - "HOSTNAME=https://localhost"
      - "REDIS_FQDN=redis"
      - "INIT=true"             # Initialze MISP, things includes, attempting to import SQL and the Files DIR
      - "CRON_USER_ID=1"        # The MISP user ID to run cron jobs as
      # Synchronization Servers settings
      - "SYNCSERVERS=${SYNCSERVERS}"
      - "SYNCSERVERS_1_NAME=${SYNCSERVERS_1_NAME}"
      - "SYNCSERVERS_1_UUID=${SYNCSERVERS_1_UUID}"
      - "SYNCSERVERS_1_KEY=${SYNCSERVERS_1_KEY}"
      - |
        SYNCSERVERS_1_DATA=
        {
          "url": "${SYNCSERVERS_1_URL}",
          "pull_rules": "{\"tags\":{\"OR\":[],\"NOT\":[]},\"orgs\":{\"OR\":[],\"NOT\":[]},\"url_params\":\"{\\\"searchanalysis\\\": \\\"2\\\"}\"}",
          "pull": true
        }
      # Custom Settings
      - "ADMIN_EMAIL=${ADMIN_EMAIL}"
      - "ADMIN_KEY=${ADMIN_KEY}"
      - "ADMIN_ORG=${ADMIN_ORG}"
      - "GPG_PASSPHRASE=${GPG_PASSPHRASE}"
      - "NSX_ANALYSIS_API_TOKEN=${NSX_ANALYSIS_API_TOKEN}"
      - "NSX_ANALYSIS_KEY=${NSX_ANALYSIS_KEY}"
      - "ORGANIZATIONS=${ORGANIZATIONS}"
      - "VIRUSTOTAL_KEY=${VIRUSTOTAL_KEY}"
  misp-modules:
    image: ostefano/misp-docker:modules-latest
    build:
      context: modules/.
      args:
        - MODULES_TAG=${MODULES_TAG}
        - MODULES_COMMIT=${MODULES_COMMIT}
    environment:
      - "REDIS_BACKEND=redis"
    depends_on:
      - redis
      - db

volumes:
    mysql_data:
